# Generated by Django 3.2.19 on 2023-07-26 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='BRAND',
        ),
    ]
