# Generated by Django 3.2.19 on 2023-07-26 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_useradrres'),
    ]

    operations = [
        migrations.DeleteModel(
            name='useradrres',
        ),
    ]
