# Generated by Django 3.2.19 on 2023-07-26 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_ordermain_ordersub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersub',
            name='ORDER',
        ),
        migrations.RemoveField(
            model_name='ordersub',
            name='PRODUCT',
        ),
        migrations.DeleteModel(
            name='ordermain',
        ),
        migrations.DeleteModel(
            name='ordersub',
        ),
    ]
