# Generated by Django 3.2.19 on 2023-07-26 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20230726_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermain',
            name='Total',
        ),
        migrations.AddField(
            model_name='ordermain',
            name='useradrs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.useradrres'),
        ),
    ]
