# Generated by Django 3.2.19 on 2023-07-27 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20230727_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='PRODCUT',
        ),
        migrations.AddField(
            model_name='rating',
            name='SUB',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.ordersub'),
        ),
    ]
