# Generated by Django 3.2.19 on 2023-07-27 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20230727_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rating',
            new_name='ratingg',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='SUB',
        ),
        migrations.AddField(
            model_name='rating',
            name='PRODUCT',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.product'),
        ),
    ]
